# Learn Basic Pandas.

In [1]:
import pandas as pd

In [2]:
data = {
    'nombre': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'edad': [25, 30, 35, 40, 45, 50, 55, 60, 65, 70],
    'ciudad': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'salario': [50000, 60000, 70000, 80000, 90000, 100000, 110000, 120000, 130000, 140000],
    'departamento': ['Ventas', 'Marketing', 'Finanzas', 'Recursos Humanos', 'Tecnología', 'Operaciones', 'Legal', 'Atención al Cliente', 'Desarrollo de Producto', 'Gestión']
}

Create dataframe with data

In [3]:
df = pd.DataFrame(data=data)
print(df)

    nombre  edad        ciudad  salario            departamento
0    Alice    25      New York    50000                  Ventas
1      Bob    30   Los Angeles    60000               Marketing
2  Charlie    35       Chicago    70000                Finanzas
3    David    40       Houston    80000        Recursos Humanos
4      Eve    45       Phoenix    90000              Tecnología
5    Frank    50  Philadelphia   100000             Operaciones
6    Grace    55   San Antonio   110000                   Legal
7    Heidi    60     San Diego   120000     Atención al Cliente
8     Ivan    65        Dallas   130000  Desarrollo de Producto
9     Judy    70      San Jose   140000                 Gestión

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nombre        10 non-null     str
 1   edad          10 non-null     int64
 2   ciudad        10 non-null     str
 3   salario       10 non-null     int64
 4   departamento  10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [5]:
df.describe()

            edad        salario
count  10.000000      10.000000
mean   47.500000   95000.000000
std    15.138252   30276.503541
min    25.000000   50000.000000
25%    36.250000   72500.000000
50%    47.500000   95000.000000
75%    58.750000  117500.000000
max    70.000000  140000.000000

In [6]:
df.shape

(10, 5)

In [8]:
df[['nombre','salario']]

    nombre  salario
0    Alice    50000
1      Bob    60000
2  Charlie    70000
3    David    80000
4      Eve    90000
5    Frank   100000
6    Grace   110000
7    Heidi   120000
8     Ivan   130000
9     Judy   140000

In [9]:
df[df['salario'] > 50000]

    nombre  edad        ciudad  salario            departamento
1      Bob    30   Los Angeles    60000               Marketing
2  Charlie    35       Chicago    70000                Finanzas
3    David    40       Houston    80000        Recursos Humanos
4      Eve    45       Phoenix    90000              Tecnología
5    Frank    50  Philadelphia   100000             Operaciones
6    Grace    55   San Antonio   110000                   Legal
7    Heidi    60     San Diego   120000     Atención al Cliente
8     Ivan    65        Dallas   130000  Desarrollo de Producto
9     Judy    70      San Jose   140000                 Gestión

In [10]:
df.max()

nombre              Judy
edad                  70
ciudad          San Jose
salario           140000
departamento      Ventas
dtype: object

In [13]:
df.sort_values(by=['salario'], ascending=[False]).head(3)

  nombre  edad     ciudad  salario            departamento
9   Judy    70   San Jose   140000                 Gestión
8   Ivan    65     Dallas   130000  Desarrollo de Producto
7  Heidi    60  San Diego   120000     Atención al Cliente