# Seconds execise cleaning data and transform data

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "nombre":  ["  Ana", "Luis ", "  Ana", "Carlos", "  Luis ", "Maria"],
    "edad":    [25, 30, 25, np.nan, 30, 22],
    "ciudad":  ["Madrid ", "  Barcelona", "Madrid ", "Sevilla", "  Barcelona", np.nan],
    "salario": [2500, 3000, 2500, 2800, 3000, np.nan],
}

In [4]:
print(data)

{'nombre': ['  Ana', 'Luis ', '  Ana', 'Carlos', '  Luis ', 'Maria'], 'edad': [25, 30, 25, nan, 30, 22], 'ciudad': ['Madrid ', '  Barcelona', 'Madrid ', 'Sevilla', '  Barcelona', nan], 'salario': [2500, 3000, 2500, 2800, 3000, nan]}

In [5]:
df = pd.DataFrame(data)

In [6]:
df.isnull().sum()

nombre     0
edad       1
ciudad     1
salario    1
dtype: int64

In [7]:
df.dropna(inplace=True)

In [9]:
df.drop_duplicates()

    nombre  edad       ciudad  salario
0      Ana  25.0      Madrid    2500.0
1    Luis   30.0    Barcelona   3000.0
4    Luis   30.0    Barcelona   3000.0

In [10]:
df

    nombre  edad       ciudad  salario
0      Ana  25.0      Madrid    2500.0
1    Luis   30.0    Barcelona   3000.0
2      Ana  25.0      Madrid    2500.0
4    Luis   30.0    Barcelona   3000.0

In [11]:
bins = [0,2000, 5000, float('inf')]
labels = ['Bajo', 'Medio', 'Alto']
df['categoria_salario'] = pd.cut(df['salario'], bins=bins, labels=labels)

In [12]:
print(df)

    nombre  edad       ciudad  salario categoria_salario
0      Ana  25.0      Madrid    2500.0             Medio
1    Luis   30.0    Barcelona   3000.0             Medio
2      Ana  25.0      Madrid    2500.0             Medio
4    Luis   30.0    Barcelona   3000.0             Medio